language: python
env:
    - TOXENV=py27
    - TOXENV=py36
    - TOXENV=cov
matrix:
    allow_failures:
        - env: TOXENV=cov
install:
    - pip install tox
script:
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet;
      coveralls;
      fi
